#+title: On the creative process
#+layout: post
#+date: 2023-11-19T19:45:00+0200
#+author: Michał Szczepanik
#+tags[]: metal
#+draft: true

Around the time when I was finishing my PhD thesis, I got into watching metal documentaries.
I know, there's a fine line between inspiration searching and procrastination.
The thesis deadline coincided with promotion period before the release of Hushed and Grim.


- Meshuggah - Making of Koloss https://www.youtube.com/watch?v=zi_nnpTf87c
- The Making of Hushed and Grim https://www.youtube.com/watch?v=9Rgi5C0JbRs
- Lamb of God - Making of Omens https://www.youtube.com/watch?v=jKh5NaqzRBU

Meshuggah

The only thing we strive for is to create something that sounds fresh.
A step into something new. Something we haven't done in the past.
That's basically how the writing process begins.

At first there's hardly anything, then nothing... Then some more, and then nothing again.
And in the end there's just an inferno.
And that's how we roll.

You both have budget constraints and a time frame to work with.
So, you can never fully do the things you want.
I mean, in your head.
In the end it will be awesome, and you're pleased, but it's not really what you aimed for.
At least with Meshuggah.

The way we work now is basically everybody at their own personal workstation.
(...)

- Lyrics - Hushed and Grim https://www.youtube.com/watch?v=5tAhlMALFmY

I guess those feelings of loss, you know, they show up and it's sort of always been a thing for us, that's sort of where we as a band put those kind of things, you know, those big losses in your life and everyone goes through it. (Brann Dailor, 0:15 in https://www.youtube.com/watch?v=5tAhlMALFmY)
I mean it's morbid to always be writing about death and destruction, but it's like... these are all coming from real places (Bill Kelliher, 1:10, same as above)

- Mastodon - Creative Process Behind 'Hushed and Grim' https://www.youtube.com/watch?v=rT1-ZP2MRFw

Everyone taking the charge of their own ideas and really putting a lot of effoert into them before it is presented to the others. (Troy Sanders, 0:07)
And then you've got three other guys, that their opinions are just as valid as yours and maybe they don't like something that you love and so there will be some compromises (Brann Dailor, 1:02)

